#!/usr/bin/env bash

# Supporting script for Votational Nelocity:
#
# It finds all markdown files - across the file system - and creates symbolic links to each of them
# in another folder. Note that the symbolic links won't have the same name as the original files,
# so that two links with the same name don't overwrite each other.
#
# Oct 2024, Michele Giugliano

# The source folder
src_folder="$HOME/Dropbox"

# The destination folder
dest_folder="$NOTES/mdlinks"

# Create the destination folder if it doesn't exist
mkdir -p "$dest_folder"

echo "Source folder:      $src_folder"
echo "Destination folder: $dest_folder"

# Delete all symbolic links in the destination folder
find "$dest_folder" -type l -delete

echo "Creating symbolic links to all markdown files in $src_folder.."
#-------------------------------------------------------------------------
# Let's use the global ignore file for fd, to exclude some folders and files
# This is useful to avoid searching in folders that are not relevant
# for example, folders containing backups.

# Let's create a local .ignore file for fd, unless it already exists
mkdir -p $HOME/.config/fd

# Let's delete the local .ignore backup, if it already exists
rm -f $HOME/.config/fd/ignore.bak

# Let's backup the original (global) .ignore file of fd
cp $HOME/.config/fd/ignore $HOME/.config/fd/ignore.bak

# Let's now create a brand new .ignore file for fd (for the current script)
echo "# The excluded folders and files" > "$HOME/.config/fd/ignore"

# The excluded folders and files
echo "$src_folder/sublime_backups/*" > "$HOME/.config/fd/ignore"
echo "$src_folder/Apps/Joplin" >> "$HOME/.config/fd/ignore"
echo "$src_folder/Pvt/Letters/PanDocLetters" >> "$HOME/.config/fd/ignore"
echo "$src_folder/Pvt/PROJECTS/LIBRO_PENSIERO" >> "$HOME/.config/fd/ignore"
echo "$src_folder/Pvt/OLDER" >> "$HOME/.config/fd/ignore"
echo "$src_folder/Pro/PUBLISHED" >> "$HOME/.config/fd/ignore"

# The excluded files (wherever they are)
echo "LICENSE.md" >> "$HOME/.config/fd/ignore"
echo "README.md" >> "$HOME/.config/fd/ignore"
echo "CHANGES.md" >> "$HOME/.config/fd/ignore"
echo "CONTRIBUTING.md" >> "$HOME/.config/fd/ignore"
echo "AUTHORS.md" >> "$HOME/.config/fd/ignore"
echo "SECURITY.md" >> "$HOME/.config/fd/ignore"
echo "CHANGELOG.md" >> "$HOME/.config/fd/ignore"
echo "HISTORY.md" >> "$HOME/.config/fd/ignore"
echo "BACKERS.md" >> "$HOME/.config/fd/ignore"
#-------------------------------------------------------------------------

echo "Starting the search and link operation.."

# Now, find all markdown files in the source folder... and link them in the destination folder
fd --case-sensitive --type file  --glob '*.md' "$src_folder" | while read -r file; do
    #echo "File: $file"
  # If a link with the same name already exists,  add a suffix to its name
    if [ -e "$dest_folder/$(basename "$file")" ]; then
        echo -n "◯"
        #echo "!! File exists: $file"
        hash=$(sha1sum "$file" | awk '{print $1}' | cut -c -5)
        salt=$(shuf -i 0-100000 -n 1)
        #echo "adding prefix: $salt-$hash"
        ln -s "$file" "$dest_folder/$salt$hash__$(basename "$file")"
    else
        echo -n "●"
        # Otherwise, create the link
        ln -s "$file" "$dest_folder/$(basename "$file")"
    fi
done

# Restore the original (global) .ignore file of fd
mv $HOME/.config/fd/ignore.bak $HOME/.config/fd/ignore

echo "Done!"
# Done
